import logging
from PIL import Image
import os

def setup_logging():
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )

    file_handler = logging.FileHandler("logs\\crop_icon.log", encoding="utf-8")
    formatter = logging.Formatter(
        "%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S"
    )
    file_handler.setFormatter(formatter)

    logging.getLogger().addHandler(file_handler)

    return logging.getLogger(__name__)

def corp_icon(shotname, iconname, crop_box):

    image_path = os.path.join(os.getcwd(), "screenshot", f"{shotname}.png")
    save_path = os.path.join(os.getcwd(), "icons", f"{iconname}.png")
    image = Image.open(image_path)
    corp_icon_image = image.crop(crop_box)
    corp_icon_image.save(save_path)
    return True


if __name__ == "__main__":
    logger = setup_logging()
    name = "cur"
    success = False
    campaign_corp = (1447, 730, 1600, 775)
    missions_corp = (900, 191, 1018, 252)
    scrimmage_corp = (791, 707, 954, 745)
    commissions_corp = (812, 592, 946, 630)
    bounty_hunts_corp = (830, 477, 964, 515)
    back_button_corp = (35, 17, 108, 84)
    home_button_corp = (1520, 20, 1570, 55)
    page_close_corp = (1526, 45, 1566, 86)
    dont_display_tick_corp = (919, 749, 1147, 773)
    login_comfirm_button_corp = (649, 583, 952, 671)
    daliy_mission_corp = (51, 246, 142, 344)
    hard_quest_crop = (1155, 160, 1502, 238)
    loading_icon_crop = (1156, 810, 1398, 851)
    black_screen_crop = (1200, 450, 1250, 500)
    menu_icon_crop = (40, 775, 120, 820)
    claim_all_1_corp = (1283, 798, 1553, 877)
    claim_all_2_corp = (1303, 798, 1573, 877)
    bounty_ticket_icon_corp = (65, 105, 210, 152)
    enter_icon_corp = (1323, 745, 1465, 825)
    reconnect_icon_crop = (806, 587, 1109, 674)
    acdemy_select_crop = (1116, 126, 1197, 155)
    request_select_icon_corp = (818, 115, 1102, 155)
    location_select_icon_corp = (822, 115, 1108, 155)
    everyday_sign_in_icon_corp = (1060, 140, 1283, 210)
    dont_display_tick2_corp = (100, 835, 220, 860)
    bounty_highway_corp = (135, 180, 485, 225)
    bounty_railway_corp = (135, 180, 485, 225)
    bounty_classroom_corp = (135, 180, 420, 225)
    entrance_crop = (1340, 580, 1460, 620)
    bounty_sweep_crop = (1080, 480, 1250, 540)
    close_button_crop = (1330, 103, 1364, 137)
    sweep_successfully = (250, 565, 365, 640)
    scrimmage_Trinity_crop = (135, 180, 215, 265)
    scrimmage_Gehenna_crop = (135, 180, 255, 265)
    scrimmage_Millennium_crop = (135, 180, 215, 265)
    normal_quest_box = (830, 160, 1160, 240)
    notice = (750, 180, 850, 240)
    declear = (750, 220, 850, 280)
    mail_box = (30, 150, 135, 190)
    task = (680, 120, 750, 150)
    sweep_successfully_2 = (720, 100, 880, 145)
    group_check_in = (685, 180, 915, 220)
    group = (70, 310, 160, 340)
    touch_to_continue = (620, 773, 980, 807)
    shop = (130, 20, 250, 50)
    task_popup = (410, 20, 530, 100)
    BA_icon = (360, 422, 428, 490)
    story = (1245, 190, 1365, 255)
    credits = (0, 140, 160, 210)
    tactical_coin = (0, 420, 220, 490)
    buy = (845, 730, 900, 760)
    cafe = (130, 20, 240, 50)
    cafe_rewards = (700, 160, 900, 220)

    menu_icon_new_crop = (173, 916, 297, 978)
    # success = corp_icon(name, "campaign_icon", campaign_corp)
    # success = corp_icon(name, "scrimmage_icon", scrimmage_corp)
    # success = corp_icon(name, "commissions_icon", commissions_corp)
    # success = corp_icon(name, "bounty_hunts_icon", bounty_hunts_corp)
    # success = corp_icon(name, "missions_icon", missions_corp)
    # success = corp_icon(name, "back_button_icon", back_button_corp)
    # success = corp_icon(name, "home_button", home_button_corp)
    # success = corp_icon(name, "page_close_icon", page_close_corp)
    # success = corp_icon(name, "dont_display_tick", dont_display_tick_corp)
    # success = corp_icon(name, "login_confirm_button2", login_comfirm_button_corp)
    # success = corp_icon(name, "daily_mission_icon", daliy_mission_corp)
    # success = corp_icon(name, "hard_quest_icon", hard_quest_crop)
    # success = corp_icon(name, "caffe_icon", caffe_icon_crop)
    # success = corp_icon(name, "menu_icon", menu_icon_crop)
    # success = corp_icon(name, "loading_icon", loading_icon_crop)
    # success = corp_icon(name, "black_screen", black_screen_crop)
    # success = corp_icon(name, "claim_all_2", claim_all_2_corp)
    # success = corp_icon(name, "reconnect_icon", reconnect_icon_crop)
    # success = corp_icon(name, "bounty_ticket_icon", bounty_ticket_icon_corp)
    # success = corp_icon(name, "scrimmage_ticket_icon", bounty_ticket_icon_corp)
    # success = corp_icon(name, "academy_select", acdemy_select_crop)
    # success = corp_icon(name, "everyday_sign_in", everyday_sign_in_icon_corp)
    # success = corp_icon(name, "request_select", request_select_icon_corp)
    # success = corp_icon(name, "location_select", location_select_icon_corp)
    # success = corp_icon(name, "dont_display_tick2", dont_display_tick2_corp)
    # success = corp_icon(name, "bounty_highway", bounty_highway_corp)
    # success = corp_icon(name, "bounty_railway", bounty_railway_corp)
    # success = corp_icon(name, "bounty_classroom", bounty_classroom_corp)
    # success = corp_icon(name, "bounty_sweep", bounty_sweep_crop)
    # success = corp_icon(name, "sweep_success", sweep_successfully)
    # success = corp_icon(name, "close_button", close_button_crop)
    # success = corp_icon(name, "entrance", entrance_crop)
    # success = corp_icon(name, "scrimmage_Trinity", scrimmage_Trinity_crop)
    # success = corp_icon(name, "scrimmage_Gehenna", scrimmage_Gehenna_crop)
    # success = corp_icon(name, "scrimmage_Millennium", scrimmage_Millennium_crop)
    # success = corp_icon(name, "normal_quest", normal_quest_box)
    # success = corp_icon(name, "declear", declear)
    # success = corp_icon(name, "mailbox", mail_box)
    # success = corp_icon(name, "task", task)
    # success = corp_icon(name, "sweep_success_2", sweep_successfully_2)
    # success = corp_icon(name, "group_ID", group)
    # success = corp_icon(name, "touch to continue", touch_to_continue)
    # success = corp_icon(name, "shop", shop)
    # success = corp_icon(name, "task_popup", task_popup)
    # success = corp_icon(name, "BA_icon", BA_icon)
    # success = corp_icon(name, "stroy", story)
    # success = corp_icon(name, "credits", credits)
    # success = corp_icon(name, "tactical_coin", tactical_coin)
    # success = corp_icon(name, "buy", buy)
    # success = corp_icon(name, "cafe", cafe)
    success = corp_icon(name, "cafe_rewards", cafe_rewards)
    # success = corp_icon(name, "menu_icon_new", menu_icon_new_crop)
    if success:
        logger.info("Icon cropped and saved successfully.")